---
- name: Debian Upgrade Playbook
  hosts: all
#   become: yes
#   become_user: root
  tasks:
    - name: Update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
